# Generated by Django 3.2.9 on 2021-12-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.PositiveSmallIntegerField(choices=[(1, 'HP'), (2, 'DELL'), (3, 'LENOVO'), (4, ',SI'), (5, 'ACER'), (6, 'SAMSUNG'), (7, 'ASUS'), (8, 'APPLE'), (9, 'TOSHIBA'), (10, 'SONY'), (11, 'RAZER'), (12, 'LG')])),
                ('name', models.CharField(max_length=300)),
                ('display', models.CharField(max_length=200)),
                ('cpu', models.CharField(max_length=200)),
                ('memory', models.CharField(max_length=200)),
                ('ssd_hdd', models.CharField(max_length=200)),
                ('graphic_card', models.CharField(max_length=200)),
                ('uses', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Used')])),
                ('model', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='product/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'product',
            },
        ),
    ]
