# Generated by Django 3.2.9 on 2021-12-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Hp', 'HP'), ('DELL', 'DELL'), ('LENOVO', 'LENOVO'), ('SI', 'SI'), ('ACER', 'ACER'), ('SAMSUNG', 'SAMSUNG'), ('ASUS', 'ASUS'), ('APPLE', 'APPLE'), ('TOSHIBA', 'TOSHIBA'), ('SONY', 'SONY'), ('RAZER', 'RAZER'), ('LG', 'LG')], default='APPLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='uses',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default='New', max_length=4),
        ),
    ]
