# Generated by Django 3.2.9 on 2021-12-12 13:43
# Generated by Django 3.2.9 on 2021-12-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'products'},
        ),
    ]
